config/routes.rb
Rails.application.routes.draw do
  get 'traveler_plans/index'

  get 'traveler_plans/show'

  get 'traveler_plans/new'

  get 'traveler_plans/create'

  get 'traveler_plans/edit'

  get 'traveler_plans/update'

  get 'traveler_plans/destory'

  get 'mailboxes/mailbox', :as => 'mailboxes'

  get 'mailboxes/compose', :as => 'mailboxes_compose'

  get 'mailboxes/readmail', :as => 'mailboxes_readmail'

  get 'mailboxes/destory'

  #get 'agents/dashboard', :as => 'agent_root'
  #get 'travelers/dashboard', :as => 'traveler_path'
  get 'agents/dashboard', :as => 'agentDashboard'
  get 'agents/profile', :as => 'agent_profile'
  
  get 'travelers/dashboard', :as => 'traveler_dashboard'
  get 'traveler_plans/new', :as => 'create_plan'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
  get "home/erroracces", :as => 'erroracces'
  
  resources :drawings
  resources :parts

  devise_for :users
  resources :users
  resources :roles
  resources :permissions
  resources :travelers
  resources :agents
  resources :traveler_plans


end

app/models/part.rb
class Part < ApplicationRecord
	#attr_accessor :name
	#attr_accessor :name
  	has_many :drawings
  	has_many :plans
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController

  before_filter :authenticate_user!
  load_and_authorize_resource
  before_filter :load_permissions

  def index
    @parts = Part.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @parts }
    end
  end

  def show
    @part = Part.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @part }
    end
  end

  def new
    @part = Part.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @part }
    end
  end

  def edit
    @part = Part.find(params[:id])
  end

  def create
    @part = Part.new(params.require(:part).permit(:name))
    #@part = Part.new(params[:part])
    #@part = Part.new(part_params)

    respond_to do |format|
      if @part.save
        format.html { redirect_to @part, notice: 'Part was successfully created.' }
        format.json { render json: @part, status: :created, location: @part }
      else
        format.html { render action: "new" }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @part = Part.find(params[:id])

    respond_to do |format|
      if @part.update_attributes(params[:part])
        format.html { redirect_to @part, notice: 'Part was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @part = Part.find(params[:id])
    @part.destroy

    respond_to do |format|
      format.html { redirect_to parts_url }
      format.json { head :no_content }
    end
  end

  private
      def part_params
        #params.require(:part).permit(:name)
        params.require(:part).permit(:name)
      end
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/parts/_form.html.erb
<%= form_for @part do |f| %>
  <% if @part.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@part.errors.count, "error")} prohibited this part from being saved:" %>
      </h2>
      <ul>
        <% @part.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <div class="actions">
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/parts/edit.html.erb
<h1>Editing part</h1>
<%= render 'form' %>
<%= link_to 'Show', @part %>
|
<%= link_to 'Back', parts_path %>

app/views/parts/index.html.erb
<h1>Listing parts</h1>
<table>
  <tr>
    <th>
      <%= 'Part Name' %>
    </th>
    <th>
      <%= 'Action' %>
    </th>
    
  </tr>
  <% @parts.each do |part| %>
    <tr>
      <td>
        <%= part.name %>
      </td>
      <td>

        <%= link_to 'Show', part if @current_permissions.include?(["Part", "show"]) %>      
        <%= link_to '| Edit', edit_part_path(part) if @current_permissions.include?(["Part", "update"]) %>     
        <%= link_to '| Destroy', part, method: :delete, data: { confirm: 'Are you sure?' } if @current_permissions.include?(["Part", "destroy"]) %>
      </td>
    </tr>
  <% end %>
</table>
<br/>
<%= link_to 'New Part', new_part_path if @current_permissions.include?(['Part', 'create']) %>

app/views/parts/new.html.erb
<h1>New part</h1>
<%= render 'form' %>
<%= link_to 'Back', parts_path %>

app/views/parts/show.html.erb
<p id="notice">
  <%= notice %>
</p>
<br/>
<%= @part.name %>

<%= link_to 'Edit | ', edit_part_path(@part)  if @current_permissions.include?(["Part", "update"]) %>
<%= link_to 'Back', parts_path %>