config/routes.rb
Rails.application.routes.draw do
  get 'traveler_plans/index'

  get 'traveler_plans/show'

  get 'traveler_plans/new'

  get 'traveler_plans/create'

  get 'traveler_plans/edit'

  get 'traveler_plans/update'

  get 'traveler_plans/destory'

  get 'mailboxes/mailbox', :as => 'mailboxes'

  get 'mailboxes/compose', :as => 'mailboxes_compose'

  get 'mailboxes/readmail', :as => 'mailboxes_readmail'

  get 'mailboxes/destory'

  #get 'agents/dashboard', :as => 'agent_root'
  #get 'travelers/dashboard', :as => 'traveler_path'
  get 'agents/dashboard', :as => 'agentDashboard'
  get 'agents/profile', :as => 'agent_profile'
  
  get 'travelers/dashboard', :as => 'traveler_dashboard'
  get 'traveler_plans/new', :as => 'create_plan'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
  get "home/erroracces", :as => 'erroracces'
  
  resources :drawings
  resources :parts

  devise_for :users
  resources :users
  resources :roles
  resources :permissions
  resources :travelers
  resources :agents
  resources :traveler_plans


end

app/models/drawing.rb
class Drawing < ApplicationRecord
	#attr_accessor :sheet_number, :part_id
  	belongs_to :part
end

app/controllers/drawings_controller.rb
class DrawingsController < ApplicationController
  
  before_filter :authenticate_user!
  load_and_authorize_resource
  before_filter :load_permissions

  def index
    @drawings = Drawing.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @drawings }
    end
  end

  def new
    @parts = Part.all
    @drawing = Drawing.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @drawing }
    end
  end

  def create
    @parts = Part.all
    #@drawing = Drawing.new(params[:drawing])
    @drawing = Drawing.new(params.require(:drawing).permit(:sheet_number,:part_id))

    respond_to do |format|
      if @drawing.save
        format.html { redirect_to @drawing, notice: 'Drawing was successfully created.' }
        format.json { render json: @drawing, status: :created, location: @drawing }
      else
        format.html { render action: "new" }
        format.json { render json: @drawing.errors, status: :unprocessable_entity }
      end
    end
  end
  def edit
   
  end
  def update
   
  end

  def destroy
    @drawing = Drawing.find(params[:id])
    @drawing.destroy

    respond_to do |format|
      format.html { redirect_to drawings_url }
      format.json { head :no_content }
    end
  end
  private
      def drawing_params
        #params.require(:part).permit(:name)
        params.require(:drawing).permit(:sheet_number, :part_id)
      end
end

app/helpers/drawings_helper.rb
module DrawingsHelper
end

app/views/drawings/_form.html.erb
<%= form_for @drawing do |f| %>
  <% if @drawing.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@drawing.errors.count, "error")} prohibited this drawing from being saved:" %>
      </h2>
      <ul>
        <% @drawing.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.select :part_id, @parts.collect{|i| [i.name, i.id]} %>
  <%= f.label :sheet_number %>
  <%= f.text_field :sheet_number %>
  <div class="actions">
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/drawings/edit.html.erb
<h1>Editing drawing</h1>
<%= render 'form' %>
<%= link_to 'Show', @drawing %>
|
<%= link_to 'Back', drawings_path %>

app/views/drawings/index.html.erb
<h1>Listing drawings</h1>
<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% @drawings.each do |drawing| %>
    <tr>
      <td>
        <%= drawing.sheet_number %>
      </td>
      <td>
        <%= link_to 'Show', drawing %>
      </td>
      <td>
        <%= link_to 'Edit', edit_drawing_path(drawing) %>
      </td>
      <td>
        <%= link_to 'Destroy', drawing, method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
</table>
<br/>
<%= link_to 'New Drawing', new_drawing_path %>

app/views/drawings/new.html.erb
<h1>New drawing</h1>
<%= render 'form' %>
<%= link_to 'Back', drawings_path %>

app/views/drawings/show.html.erb
<p id="notice">
  <%= notice %>
</p>
<%= @drawing.sheet_number %>
<%= link_to 'Edit', edit_drawing_path(@drawing) %>
|
<%= link_to 'Back', drawings_path %>