config/routes.rb
Rails.application.routes.draw do
  get 'traveler_plans/index'

  get 'traveler_plans/show'

  get 'traveler_plans/new'

  get 'traveler_plans/create'

  get 'traveler_plans/edit'

  get 'traveler_plans/update'

  get 'traveler_plans/destory'

  get 'mailboxes/mailbox', :as => 'mailboxes'

  get 'mailboxes/compose', :as => 'mailboxes_compose'

  get 'mailboxes/readmail', :as => 'mailboxes_readmail'

  get 'mailboxes/destory'

  #get 'agents/dashboard', :as => 'agent_root'
  #get 'travelers/dashboard', :as => 'traveler_path'
  get 'agents/dashboard', :as => 'agentDashboard'
  get 'agents/profile', :as => 'agent_profile'
  
  get 'travelers/dashboard', :as => 'traveler_dashboard'
  get 'traveler_plans/new', :as => 'create_plan'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
  get "home/erroracces", :as => 'erroracces'
  
  resources :drawings
  resources :parts

  devise_for :users
  resources :users
  resources :roles
  resources :permissions
  resources :travelers
  resources :agents
  resources :traveler_plans


end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
    user.role.permissions.each do |permission|
      if permission.subject_class == "all"
        can permission.action.to_sym, permission.subject_class.to_sym
      else
        can permission.action.to_sym, permission.subject_class.constantize
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drawing.rb
class Drawing < ApplicationRecord
	#attr_accessor :sheet_number, :part_id
  	belongs_to :part
end

app/models/mailbox.rb
class Mailbox < ApplicationRecord
end

app/models/part.rb
class Part < ApplicationRecord
	#attr_accessor :name
	#attr_accessor :name
  	has_many :drawings
  	has_many :plans
end

app/models/permission.rb
class Permission < ApplicationRecord
	#attr_accessor :subject_class, :action, :name
end

app/models/role.rb
class Role < ApplicationRecord
	#attr_accessor :name

  	has_many :users
  	has_and_belongs_to_many :permissions

  	validates :name, presence: true, uniqueness: true

  	def set_permissions(permissions)
	    permissions.each do |id|
	      permission = Permission.find(id)
	      self.permissions << permission
	      case permission.subject_class
	      when "Part"
	        case permission.action
	        when "create"
	          self.permissions << Permission.where(subject_class: "Drawing", action: "create")
	        when "update"
	          self.permissions << Permission.where(subject_class: "Drawing", action: ["update", "destroy"])
	        end
	      end
	    end
  	end
end

app/models/traveler_plan.rb
class TravelerPlan < ApplicationRecord
#attr_accessible :plan_name, :plan_description
	#attr_writer :current_step
#validates_presence_of :plan_name, :if => lambda { |o| o.current_step == "plan" }
#validates_presence_of :plan_description, :if => lambda { |o| o.current_step == "description" }

validates :plan_name, presence: true, if: :step1?
validates :plan_short_description, presence: true, if: :step2?
validates :is_active, presence: true, if: :step3?

include MultiStepModel

  def self.total_steps
    3
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  #attr_accessor :email, :password, :password_confirmation, :remember_me, :role_id, :name

  belongs_to :role

  def super_admin?
    self.role.name == "Super Admin"
  end
  def traveler?
    self.role.name == "Traveler"
  end
  def agent?
    self.role.name == "Agent"
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :authenticate_user!
  before_filter :load_permissions

  def index
  end

end

app/controllers/parts_controller.rb
class PartsController < ApplicationController

  before_filter :authenticate_user!
  load_and_authorize_resource
  before_filter :load_permissions

  def index
    @parts = Part.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @parts }
    end
  end

  def show
    @part = Part.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @part }
    end
  end

  def new
    @part = Part.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @part }
    end
  end

  def edit
    @part = Part.find(params[:id])
  end

  def create
    @part = Part.new(params.require(:part).permit(:name))
    #@part = Part.new(params[:part])
    #@part = Part.new(part_params)

    respond_to do |format|
      if @part.save
        format.html { redirect_to @part, notice: 'Part was successfully created.' }
        format.json { render json: @part, status: :created, location: @part }
      else
        format.html { render action: "new" }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @part = Part.find(params[:id])

    respond_to do |format|
      if @part.update_attributes(params[:part])
        format.html { redirect_to @part, notice: 'Part was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @part = Part.find(params[:id])
    @part.destroy

    respond_to do |format|
      format.html { redirect_to parts_url }
      format.json { head :no_content }
    end
  end

  private
      def part_params
        #params.require(:part).permit(:name)
        params.require(:part).permit(:name)
      end
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drawings_helper.rb
module DrawingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mailboxes_helper.rb
module MailboxesHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/travelers_helper.rb
module TravelersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Devise Roles" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Devise Roles" %>">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    
  </head>
  <body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
      <header class="main-header">
        <%= render 'layouts/partial/navigation' %>
      </header>
      <%= render 'layouts/partial/sidebar' %>
        <div class="content-wrapper">
          <%= render 'layouts/partial/messages' %>
            <section class="content">
              <%= yield %>
            </section>
        </div>
        <%= render 'layouts/partial/footer' %> 
    </div> 
      <!-- ./wrapper -->
 
    <script>
      $(function () {
        $("#example1").DataTable({
            "paging": true,
        });
        $('#example2').DataTable({
          "paging": true,
          "lengthChange": false,
          "searching": false,
          "ordering": true,
          "info": true,
          "autoWidth": false
        });
      });
    </script>
  </body>
</html>

app/views/layouts/dashboard_agent.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Devise Roles" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Devise Roles" %>">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

    <%= stylesheet_link_tag 'agent' %>
    <%= javascript_include_tag 'agent' %>
    <%= csrf_meta_tags %>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
      <header class="main-header">
        <%= render 'layouts/partial/navigation' %>
      </header>
      <%= render 'layouts/partial/sidebar' %>
        <div class="content-wrapper">
          <%= render 'layouts/partial/messages' %>
            <section class="content">
              <%= yield %>
            </section>
        </div>
        <%= render 'layouts/partial/footer' %> 
    </div> 
      <!-- ./wrapper -->
 
    <script>
      $(function () {
        $("#example1").DataTable({
            "paging": true,
        });
        $('#example2').DataTable({
          "paging": true,
          "lengthChange": false,
          "searching": false,
          "ordering": true,
          "info": true,
          "autoWidth": false
        });
      });
    </script>
  </body>
</html>

app/views/layouts/dashboard_superadmin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Devise Roles" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Devise Roles" %>">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "dashboard2" %>
    <%= csrf_meta_tags %>
    
  </head>
  <body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
      <header class="main-header">
        <%= render 'layouts/partial/navigation' %>
      </header>
      <%= render 'layouts/partial/sidebar' %>
        <div class="content-wrapper">
          <%= render 'layouts/partial/messages' %>
            <section class="content">
              <%= yield %>
            </section>
        </div>
        <%= render 'layouts/partial/footer' %> 
    </div> 
      <!-- ./wrapper -->
 
    <script>
      $(function () {
        $("#example1").DataTable({
            "paging": true,
        });
        $('#example2').DataTable({
          "paging": true,
          "lengthChange": false,
          "searching": false,
          "ordering": true,
          "info": true,
          "autoWidth": false
        });
      });
    </script>
  </body>
</html>

app/views/layouts/dashboard_traveler.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Devise Roles" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Devise Roles" %>">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

    <%= stylesheet_link_tag 'agent' %>
    <%= javascript_include_tag 'agent' %>
    <%= csrf_meta_tags %>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
      <header class="main-header">
        <%= render 'layouts/partial/navigation' %>
      </header>
      <%= render 'layouts/partial/sidebar' %>
        <div class="content-wrapper">
          <%= render 'layouts/partial/messages' %>
            <section class="content">
              <%= yield %>
            </section>
        </div>
        <%= render 'layouts/partial/footer' %> 
    </div> 
      <!-- ./wrapper -->
 
    <script>
      $(function () {
        $("#example1").DataTable({
            "paging": true,
        });
        $('#example2').DataTable({
          "paging": true,
          "lengthChange": false,
          "searching": false,
          "ordering": true,
          "info": true,
          "autoWidth": false
        });
      });
    </script>
  </body>
</html>

app/views/layouts/errors.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Devise Roles" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Devise Roles" %>">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

    <%= stylesheet_link_tag 'errors' %>
    <%= javascript_include_tag 'errors' %>
    <%= csrf_meta_tags %>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
      <header class="main-header">
        <%= render 'layouts/partial/navigation' %>
      </header>
      <%= render 'layouts/partial/sidebar' %>
        <div class="content-wrapper">
            <%= render 'layouts/partial/messages' %>
            <section class="content">
                <div class="error-page">
                  <%= yield %>
                </div>  
            </section>
        </div>
        <%= render 'layouts/partial/footer' %> 
    </div> 
      <!-- ./wrapper -->
 
    <script>
      $(function () {
  //Add text editor
    $("#compose-textarea").wysihtml5();
    //Enable iCheck plugin for checkboxes
    //iCheck for checkbox and radio inputs
    $('.mailbox-messages input[type="checkbox"]').iCheck({
      checkboxClass: 'icheckbox_flat-blue',
      radioClass: 'iradio_flat-blue'
    });

    //Enable check and uncheck all functionality
    $(".checkbox-toggle").click(function () {
      var clicks = $(this).data('clicks');
      if (clicks) {
        //Uncheck all checkboxes
        $(".mailbox-messages input[type='checkbox']").iCheck("uncheck");
        $(".fa", this).removeClass("fa-check-square-o").addClass('fa-square-o');
      } else {
        //Check all checkboxes
        $(".mailbox-messages input[type='checkbox']").iCheck("check");
        $(".fa", this).removeClass("fa-square-o").addClass('fa-check-square-o');
      }
      $(this).data("clicks", !clicks);
    });

    //Handle starring for glyphicon and font awesome
    $(".mailbox-star").click(function (e) {
      e.preventDefault();
      //detect type
      var $this = $(this).find("a > i");
      var glyph = $this.hasClass("glyphicon");
      var fa = $this.hasClass("fa");

      //Switch states
      if (glyph) {
        $this.toggleClass("glyphicon-star");
        $this.toggleClass("glyphicon-star-empty");
      }

      if (fa) {
        $this.toggleClass("fa-star");
        $this.toggleClass("fa-star-o");
      }
    });
  });
    </script>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Devise Roles" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Devise Roles" %>">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

    <%= stylesheet_link_tag 'login' %>
    <%= javascript_include_tag 'login' %>
    <%= csrf_meta_tags %>
    
  </head>
  <body class="hold-transition login-page">
    <div class="login-box">
      <%= render 'layouts/partial/messages' %>
      <%= yield %>
    </div> 
      <!-- ./wrapper -->
  </body>
</html>

app/views/layouts/mailboxes.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Devise Roles" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Devise Roles" %>">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

    <%= stylesheet_link_tag 'mailboxes' %>
    <%= javascript_include_tag 'mailboxes' %>
    <%= csrf_meta_tags %>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
      <header class="main-header">
        <%= render 'layouts/partial/navigation' %>
      </header>
      <%= render 'layouts/partial/sidebar' %>
        <div class="content-wrapper">
            <%= render 'layouts/partial/messages' %>
            <section class="content">
              <div class="row">
                <%= render 'layouts/partial/mailbox_mid_sidebar' %>
                <%= yield %>
              </div>
            </section>
        </div>
        <%= render 'layouts/partial/footer' %> 
    </div> 
      <!-- ./wrapper -->
 
    <script>
      $(function () {
  //Add text editor
    $("#compose-textarea").wysihtml5();
    //Enable iCheck plugin for checkboxes
    //iCheck for checkbox and radio inputs
    $('.mailbox-messages input[type="checkbox"]').iCheck({
      checkboxClass: 'icheckbox_flat-blue',
      radioClass: 'iradio_flat-blue'
    });

    //Enable check and uncheck all functionality
    $(".checkbox-toggle").click(function () {
      var clicks = $(this).data('clicks');
      if (clicks) {
        //Uncheck all checkboxes
        $(".mailbox-messages input[type='checkbox']").iCheck("uncheck");
        $(".fa", this).removeClass("fa-check-square-o").addClass('fa-square-o');
      } else {
        //Check all checkboxes
        $(".mailbox-messages input[type='checkbox']").iCheck("check");
        $(".fa", this).removeClass("fa-square-o").addClass('fa-check-square-o');
      }
      $(this).data("clicks", !clicks);
    });

    //Handle starring for glyphicon and font awesome
    $(".mailbox-star").click(function (e) {
      e.preventDefault();
      //detect type
      var $this = $(this).find("a > i");
      var glyph = $this.hasClass("glyphicon");
      var fa = $this.hasClass("fa");

      //Switch states
      if (glyph) {
        $this.toggleClass("glyphicon-star");
        $this.toggleClass("glyphicon-star-empty");
      }

      if (fa) {
        $this.toggleClass("fa-star");
        $this.toggleClass("fa-star-o");
      }
    });
  });
    </script>
  </body>
</html>

app/views/layouts/partial/_breadcrumbs.html.erb
 <section class="content-header">
  <h1>
    Dashboard
    <small>Version 2.0</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Dashboard</li>
  </ol>
</section>

app/views/layouts/partial/_header.html.erb
<% mod ||= nil %>
<% if mod %>
  <% if !signed_in? %>
    <div class="clear"></div>
  <% else %>
    <%= render "/layouts/#{mod}_navigation" %>
  <% end %>
<% else %>
  <div class="clearfix"></div>
<% end %>

app/views/layouts/partial/_mailbox_mid_sidebar.html.erb
<div class="col-md-3">
  <a href="<%= mailboxes_compose_path %>" class="btn btn-primary btn-block margin-bottom">Compose</a>

  <div class="box box-solid">
    <div class="box-header with-border">
      <h3 class="box-title">Folders</h3>

      <div class="box-tools">
        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
        </button>
      </div>
    </div>
    <div class="box-body no-padding">
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><a href="#"><i class="fa fa-inbox"></i> Inbox
          <span class="label label-primary pull-right">12</span></a></li>
        <li><a href="#"><i class="fa fa-envelope-o"></i> Sent</a></li>
        <li><a href="#"><i class="fa fa-file-text-o"></i> Drafts</a></li>
        <li><a href="#"><i class="fa fa-filter"></i> Junk <span class="label label-warning pull-right">65</span></a>
        </li>
        <li><a href="#"><i class="fa fa-trash-o"></i> Trash</a></li>
      </ul>
    </div>
    <!-- /.box-body -->
  </div>
  <!-- /. box -->
  <div class="box box-solid">
    <div class="box-header with-border">
      <h3 class="box-title">Labels</h3>

      <div class="box-tools">
        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
        </button>
      </div>
    </div>
    <div class="box-body no-padding">
      <ul class="nav nav-pills nav-stacked">
        <li><a href="#"><i class="fa fa-circle-o text-red"></i> Important</a></li>
        <li><a href="#"><i class="fa fa-circle-o text-yellow"></i> Promotions</a></li>
        <li><a href="#"><i class="fa fa-circle-o text-light-blue"></i> Social</a></li>
      </ul>
    </div>
    <!-- /.box-body -->
  </div>
  <!-- /.box -->
</div>

app/views/layouts/partial/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/partial/_nav_links_for_auth.html.erb
   <%
=begin %>
	<% if user_signed_in? %>

   <li><%= link_to 'Edit account', edit_user_registration_path %></li>
   <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
   <%

   <li class="dropdown">
	  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Manage<span class="caret"></span></a>
	  <ul class="dropdown-menu" role="menu">
	    <li><a href="#">Action</a></li>
	    <li><a href="#">Another action</a></li>
	    <li><a href="#">Something else here</a></li>
	    <li class="divider"></li>
	    <li><a href="#">Separated link</a></li>
	    <li class="divider"></li>
	    <li><%= link_to "Roles", roles_path if current_user.super_admin? %></li>
	    <li><%= link_to "Permissions", permissions_path if current_user.super_admin? %></li>
	  </ul>
	</li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>
   <%
=end %>

app/views/layouts/partial/_profile_tabber_nav.html.erb
<ul class="nav nav-tabs">
  <li class="active"><a href="#activity" data-toggle="tab">Activity</a></li>
  <li><a href="#timeline" data-toggle="tab">Timeline</a></li>
  <li><a href="#settings" data-toggle="tab">Settings</a></li>
</ul>