config/routes.rb
Rails.application.routes.draw do
  get 'traveler_plans/index'

  get 'traveler_plans/show'

  get 'traveler_plans/new'

  get 'traveler_plans/create'

  get 'traveler_plans/edit'

  get 'traveler_plans/update'

  get 'traveler_plans/destory'

  get 'mailboxes/mailbox', :as => 'mailboxes'

  get 'mailboxes/compose', :as => 'mailboxes_compose'

  get 'mailboxes/readmail', :as => 'mailboxes_readmail'

  get 'mailboxes/destory'

  #get 'agents/dashboard', :as => 'agent_root'
  #get 'travelers/dashboard', :as => 'traveler_path'
  get 'agents/dashboard', :as => 'agentDashboard'
  get 'agents/profile', :as => 'agent_profile'
  
  get 'travelers/dashboard', :as => 'traveler_dashboard'
  get 'traveler_plans/new', :as => 'create_plan'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
  get "home/erroracces", :as => 'erroracces'
  
  resources :drawings
  resources :parts

  devise_for :users
  resources :users
  resources :roles
  resources :permissions
  resources :travelers
  resources :agents
  resources :traveler_plans


end

app/models/role.rb
class Role < ApplicationRecord
	#attr_accessor :name

  	has_many :users
  	has_and_belongs_to_many :permissions

  	validates :name, presence: true, uniqueness: true

  	def set_permissions(permissions)
	    permissions.each do |id|
	      permission = Permission.find(id)
	      self.permissions << permission
	      case permission.subject_class
	      when "Part"
	        case permission.action
	        when "create"
	          self.permissions << Permission.where(subject_class: "Drawing", action: "create")
	        when "update"
	          self.permissions << Permission.where(subject_class: "Drawing", action: ["update", "destroy"])
	        end
	      end
	    end
  	end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :is_super_admin?

  def index
    @roles = Role.all{|i| i.name != "Super Admin"}
  end
  def new
    @role = Role.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @role }
    end
  end
  def create
    @role = Role.new(params.require(:role).permit(:name))

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render json: @role, status: :created, location: @role }
      else
        format.html { render action: "new" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end
  def show
    @role = Role.find(params[:id])
    @permissions = @role.permissions
  end

  def edit
    @role = Role.find(params[:id])
    @permissions = Permission.all{|i| ["Part"].include? i.subject_class}.compact
    @role_permissions = @role.permissions.collect{|p| p.id}
  end

  def update
    @role = Role.find(params[:id])
    @role.permissions = []
    @role.set_permissions(params[:permissions]) if params[:permissions]
    if @role.save
      redirect_to roles_path and return
    end
    @permissions = Permission.all{|i| ["Part"].include? i.subject_class}.compact
    render 'edit'
  end

  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    respond_to do |format|
      format.html { redirect_to roles_url }
      format.json { head :no_content }
    end
  end
  
  private

  def is_super_admin?
    redirect_to root_path and return unless current_user.super_admin?
  end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/edit.html.erb
<div class="row">
  <div class="span16">
    <%= form_for( @role, :url => role_path, :method => :put) do |f| %>
      <fieldset>
        <legend>Role</legend>
        <br/>
        <%= @role.name %>
        <br/>
        Permissions
        <br/>
        <table>
          <tr>
            <th>Class</th>
            <th>Action</th>
            <th>#{check_box_tag 'main', 0, false}</th>
          </tr>
          <% @permissions.each do |permission| %>
            <tr>
              <td>
                <%= permission.subject_class %>
              </td>
              <td>
                <%= permission.action %>
              </td>
              <td>
                <%= check_box_tag 'permissions[]', permission.id, @role_permissions.include?(permission.id), {array: true, class: "check_box"}  %>
              </td>
            </tr>
          <% end %>
        </table>
        <div class="span16 offset2">
          <div class="clearfix">
            <%= f.submit "Update", :class => 'btn primary' %>
            <%= link_to 'Cancel', roles_path %>
          </div>
        </div>
      </fieldset>
    <% end %>
  </div>
</div>

app/views/roles/index.html.erb
<div class="container">
  <div class="row">
    <h3>Super Admin: Listing Roles</h3>
    <div class="col-md-12">
      <%= link_to '', new_role_path, :title=>'Create New Role', :class => 'pull-right glyphicon glyphicon-plus' if current_user.super_admin? %>
      <table class="table">
        <thead>
          <th>Name</th>
          <th></th>
          <th></th>
          <th></th>
        </thead>
        <tbody>
          <% @roles.each do |role| %>
          <tr>
            <td>
              <%= role.name %>
            </td>
            <td>
              <%= link_to '', role, :class => 'glyphicon glyphicon-eye-open', :title=>'View' %>
            </td>
            <td>
              <%= link_to '', edit_role_path(role), :class => 'glyphicon glyphicon-pencil', :title=>'Edit Your Role'  %>
            </td>
            <td>
             <%= link_to '', role, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'glyphicon glyphicon-remove', :title=>'Delete Your Role' %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/roles/new.html.erb
<%
=begin %>
<div class="row">
  <div class="span16">
    <%= form_for( @role, :url => role_path, :method => :put) do |f| %>
      <fieldset>
        <legend>Role</legend>
        <br/>
        <%= @role.name %>
        <br/>
        Permissions
        <br/>
        <table>
          <tr>
            <th>Class</th>
            <th>Action</th>
            <th>#{check_box_tag 'main', 0, false}</th>
          </tr>
          <% @permissions.each do |permission| %>
            <tr>
              <td>
                <%= permission.subject_class %>
              </td>
              <td>
                <%= permission.action %>
              </td>
              <td>
                <%= check_box_tag 'permissions[]', permission.id, @role_permissions.include?(permission.id), {array: true, class: "check_box"}  %>
              </td>
            </tr>
          <% end %>
        </table>
        <div class="span16 offset2">
          <div class="clearfix">
            <%= f.submit "Update", :class => 'btn primary' %>
            <%= link_to 'Cancel', roles_path %>
          </div>
        </div>
      </fieldset>
    <% end %>
  </div>
</div>
<%
=end %>
<div class="row">
  <div class="col-md-12">
    <div class="authform">
      <h3>Role <%= @role.name %></h3>
      <%= form_for @role do |f| %>
        <% if @role.errors.any? %>
          <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h2>
              <%= "#{pluralize(@role.errors.count, "error")} prohibited this role from being saved:" %>
            </h2>
            <ul>
              <% @role.errors.full_messages.each do |msg| %>
                <li>
                  <%= msg %>
                </li>
              <% end %>
            </ul>
          </div>

        <% end %>
        <fieldset>
         <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name %>
          </div>
          

        </fieldset>
          <div class="clearfix"></div>
          <div class="form-group pull-right">
            <%= f.submit "Save", :class => 'btn primary' %>
            <%= link_to 'Cancel', roles_path, :class => 'btn primary' %>
          </div>
          
      <% end %>
    </div>
  </div>
</div>

app/views/roles/show.html.erb
<%
=begin %><p id="notice">
  <%= notice %>
</p>
<p>
  <b>Name:</b>
  <%= @role.name %>
</p>
Permissions
<table>
  <tr>
    <th>Class</th>
    <th>Action</th>
  </tr>
  <% @permissions.each do |permission| %>
    <tr>
      <td>
        <%= permission.subject_class %>
      </td>
      <td>
        <%= permission.action %>
      </td>
    </tr>
  <% end %>
</table>
<%= link_to 'Back', roles_path %>
<%
=end %>
<div class="container">
  <div class="row">
    <div class="col-md-12"><p id="notice"><%= notice %></p></div>
  </div>  
  <div class="row">
    <h3>Name: <%= @role.name %></h3>
    <div class="col-md-12">
      <table class="table">
        <thead>
          <th>Class</th>
          <th>Action</th>
        </thead>
        <tbody>
          <% @permissions.each do |permission| %>
            <tr>
              <td>
                <%= permission.subject_class %>
              </td>
              <td>
                <%= permission.action %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to 'Back', roles_path, :class => 'btn btn-default' %>
    </div>
  </div>
</div>